lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Looks for version and node documents with an integer version of  -1, indicating
that the save failed before updating can occur.
If the corresponding sample doc doesn't exist or doesn't contain the uuid
version for the version/node doc, then the version is deleted from the
system assuming at least an hour has passed since they were saved.
Otherwise, the version and node docs are updated with the appropriate integer
version.

check db integrity on startup

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

... rather than relying on garbage collector.
Think it was interfering with other tests by deleting docs during the save
process.

Explicitly turn off db correcting code in tests

---

lib/SampleService/SampleServiceServer.py
test/SampleService_test.py

The py server reprs the contents of the exception's args tuple, which in
the case of ('some string',) will result in an exception message of
"'some string'".
Bug was introduced here: https://github.com/kbase/kb_sdk/pull/323

Fix bug in py server & add failing save test

---

lib/SampleService/core/api_arguments.py
test/SampleService_test.py
test/core/api_arguments_test.py

Too easy to accidentally blow away the current acls otherwise

Require acls key to be present and a dict in replace acls method

---

lib/SampleService/core/acls.py
lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
lib/SampleService/core/storage/errors.py
test/SampleService_test.py
test/core/storage/arango_sample_storage_test.py

If the owner has changed between  fetching acls from the DB and saving back
updated ACLs, the owner might also be listed in admin/write/read ACLs.
This change ensures that the owner hasn't changed since the ACLs were
retrieved.
Next is to check that the ACLs are consistent  - e.g. no user appears more than
once in the ACLs.

Fix race condition on setting acls

---

README.md

The dynamic service manager will just start the old container if there's no new
commit, even if the catalog parameters for the module have changed. This means
the deploy.cfg file is not updated with the new parameters and so the
service will still fail to start.

Trivial change because dynamic services are stupid

---

README.md
TODO.md
lib/SampleService/core/config.py
lib/SampleService/core/samples.py
lib/SampleService/core/validators/builtin.py
test/core/config_test.py
test/core/config_test_vals.py
test/core/samples_test.py
test/core/validators/builtin_test.py

Means validator code has to import service code, bleah. Return string instead.

Don't throw an error in validator on bad meta

---

lib/SampleService/core/config.py
lib/SampleService/core/samples.py
test/core/config_test.py
test/core/samples_test.py

as opposed to a single validator. Allows for writing simpler, more general
validators and applying them in combination on keys for more complex
validations.
Still need to make the configuration file / parser handle multiple
validators.

Make core code take a list of validators per key

---

Pipfile
Pipfile.lock
README.md
TODO.md
lib/SampleService/core/config.py
lib/SampleService/core/samples.py
lib/SampleService/core/validators/builtin.py
test/core/samples_test.py
test/core/validators/builtin_test.py

Will be needed for the case where the validators do not exactly match a
key, e.g. prefixes.

Pass metadata keys to validators

---

lib/SampleService/core/api_translation.py
test/core/api_arguments_test.py

Skipping the check implies the user is not acting as an admin. Reduces code
in the Impl class.

Add option to skip admin check and return false

---

lib/SampleService/core/config.py
test/SampleService_test.py
test/core/config_test.py

Since keys will have key-specific metadata and that MD may be different
for prefix and standard keys, can't have prefix and std validators under
the same key in the config

Separate prefix & std keys in config

---

lib/SampleService/core/config.py
test/core/storage/arango_sample_storage_test.py

Add a test that ensures the self correction code is run when a problem is
detected in the version doc when linking data.
Also turn on the consistency checker, can't believe I missed that.

Add test for data linking self-correction code, turn on consistency checker

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Use link class in db layer

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

IOW, if the link created + expired times don't overlap, don't count it

Only count extant links against max

---

lib/SampleService/core/acls.py
lib/SampleService/core/api_translation.py
lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
lib/SampleService/core/user.py
lib/SampleService/core/user_lookup.py
test/SampleService_test.py
test/core/acls_test.py
test/core/api_translation_test.py
test/core/samples_test.py
test/core/storage/arango_sample_storage_test.py

lots of knock on effects again
Think that's it for bare usernames outside of the API layer

Use user id class in ACLs

---

lib/SampleService/core/user.py
test/core/storage/arango_sample_storage_test.py
test/core/user_test.py

Since they're being stored in the db

Add a max length for user names

---

design/link_ws_data_to_sample_in_RE.md

At the start of the document, it is explicitly said that if a user has
access to data, the user also has access to any linked samples and does
not need read permissions for the samples. This is contradicted later on in
the document. The first design is correct, and is how the link implementation
currently works. Remove the contradictory text.

Fix inconsistency in link design document

---

lib/SampleService/core/samples.py
test/SampleService_test.py
test/core/samples_test.py

Not sure what to do about deleted workspaces. Document issue for now.
Maybe auto expire if workspace is deleted? But what about undelete?
Links shouldn't be visible to users anyway with current access methods.

Allow expiring links from deleted objects

---

lib/SampleService/core/workspace.py
test/core/workspace_test.py

for permission checks. Will be used for sample service admins to create links to
workspace objects for which they don't have write permission.

Allow passing NONE for the required ws perm

---

lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/samples.py
test/core/samples_test.py

Allows saving over another user's sample if you're an admin
Next up exposing in API

Add as_admin arg to save_sample core code

---

README.md
lib/SampleService/core/config.py
test/core/config_test.py

Allow `-` as well for now, but remove soon (after Sebastian updates cfg yml)
Intentionally do not document the soon to be removed `-` form
Fixes https://github.com/kbase/sample_service/issues/285

Consistently use _ in validator config

---

Pipfile
Pipfile.lock
deploy.cfg
lib/SampleService/core/config.py
lib/SampleService/core/notification.py
test/SampleService_test.py
test/kafka_controller.py
test/mongo_controller.py

That was a major pain.
* deleting a topic & contents takes ~2s locally, tripled test time when
run after every test
* Kafka consumer polling is pretty slow, and can't be done mid test if
assert _close_to_now is used.
* It seems as though not closing clients can cause weird errors/hangs in
other clients? Not 100% sure about this, was making too many changes
too rapidly trying to figure out what was going on. Closing doesn't seem
to hurt  though.
also flake8 mysteriously started whining about new stuff even though it
wasn't updated.

Integrate kafka notifier into service

---

lib/SampleService/core/notification.py
lib/SampleService/core/samples.py
test/SampleService_test.py
test/core/samples_test.py

Consuming messages from kafka seems to take 1-2s, so doing so after every
test is too expensive. Consuming at the start of tests where it matters

Integrate acl change notifications into service

---

lib/SampleService/core/notification.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Return expired link ID from create link

---

lib/SampleService/core/notification.py
test/SampleService_test.py

will need both for link creation

Add new and expired links to notifications class

---

lib/SampleService/core/samples.py
test/core/samples_test.py

Return created link from core code

---

lib/SampleService/core/acls.py
lib/SampleService/core/api_translation.py
lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/acls_test.py
test/core/api_translation_test.py
test/core/sample_test.py
test/core/samples_test.py
test/core/storage/arango_sample_storage_test.py

This will be needed for resending Kafka messages in a date range, e.g.
looking for updates in a given time range.
Not exposed in API for now.

Record time sample acls are changed

---

lib/SampleService/core/config.py
test/SampleService_test.py
test/core/config_test.py

Replaced by callable_builder
Fixes https://github.com/kbase/sample_service/issues/285

Remove callable-builder as a validator config key

---

Makefile

Seems like the \ on the comment is causing the compile step to be skipped?

Fix registration

---

TODO.md
lib/SampleService/core/workspace.py
test/SampleService_test.py
test/core/workspace_test.py

Requires supporting public workspaces as well, which up to now were not supported.
Added a couple of integration tests for public workspaces for the 2 methods
that only require read access now that public workspaces work.

Support anonymous users in ws wrapper has_permission method

---

lib/SampleService/core/acls.py
test/core/acls_test.py

Checks if a SampleACLDelta is actually an update.
Originally in the ArangoSampleStorage class but testing it there was a pain.
Easier here and more resuable.

Add is_update method to SampleACL

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/acls_test.py
test/core/storage/arango_sample_storage_test.py

Granular updates, as opposed to replace_sample_acls

Add update_sample_acls to database

---

lib/SampleService/core/samples.py

Factor out a user check method

---

lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/samples_test.py
test/core/storage/arango_sample_storage_test.py

No need for them to be in the same class, makes the API more complicated
than it needs to be

Step 1 in separating update time from update ACLs

---

lib/SampleService/core/acls.py
lib/SampleService/core/samples.py
test/core/acls_test.py
test/core/samples_test.py
test/core/storage/arango_sample_storage_test.py

Remove update time from ACL delta class

---

lib/SampleService/core/acls.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

When a user already exists in an ACL, adding them to another ACL  wouldn't
remove them from the first

Fix acl update bug

---

Makefile

Example:
make test-sdkless TEST_SPEC=test/core/sample_test.py
By default will run all tests

Allow setting the test discovery instructions for pytest

---

lib/SampleService/core/sample.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Older samples will not have the source field, so handle that case
without a KeyError

Backwards compatibility for source metadata

---

lib/SampleService/core/acls.py
test/core/acls_test.py

Signifies that user permissions should not be downgraded if current
permission is greater than the permission in the acl delta

At at_least option to acl delta value class

---

lib/SampleService/core/acls.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Currently if a user is in an admin ACL and read acls are requested for
that user, they will be demoted from admin. The DB layer now supports
the `at_least` toggle so that if users have at least the requested
permission their permissions are not altered.

Add option to update acls without demoting current users in DB layer

---

lib/SampleService/core/acls.py
lib/SampleService/core/storage/arango_sample_storage.py
test/arango_controller.py
test/core/acls_test.py
test/core/storage/arango_sample_storage_test.py

1) at_least didn't apply to the owner
2) at_least wasn't taken into account when determining whether an ACL update
was a no-op.

Fix bugs in ACL updates with at_least = True 

---

.github/workflows/non_sdk_test.yml
lib/SampleService/core/validator/builtin.py
test/core/validator/builtin_test.py

The ontology validator requires a service wizard URL as a paramter.
That URL varies across deploys so it shouldn't be in the validator
config.  This changes it so that the URL is figured out through the
deploy config file.

Drop service wizard url as a parameter

---

lib/SampleService/core/config.py
test/core/config_test.py

We would like to start packing more information into the key_metadata
including nested structures.  So let's relax this check.  We may
want to add some constraints later once we know what we need.

Extend allowed data in key_metadata

---

lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
test/SampleService_test.py

* Creates new arango method that will grab all linked data types in one query rather than one per sample
* Also  Handles ACL checks for `get_data_links_from_sample_set` in bulk so that they are all checked using only one AQL query
* Performance improvements from running local tests appear to be about ~15x faster than several singular calls

SAM-151: Optimize get bulk data links

---

lib/SampleService/core/storage/arango_sample_storage.py

Fixes `update_sample_acls` to prevent erroneous "owner unexpectedly changed" errors from being thrown due to a bad count of changed documents.

SAM-198 Fix update_sample_acls to prevent erronious errors

---

.github/workflows/non_sdk_test.yml
lib/SampleService/core/storage/arango_sample_storage.py

Adds a check to the `_check_col_updated` update condition like the one in `_deletion_delay`.

SAM-200 Fix Reaper-instigated write-write errors
