kbase/sample_service

Dockerfile
Makefile
Pipfile
Pipfile.lock
TODO.md
lib/SampleService/SampleServiceImpl.py
test/SampleService_server_test.py
test/coveragerc_sdk

Ignore generated files other than impl
Use pytest, nose is abandonware

Make kb-sdk test pass and report coverage

---

test/core/arango_controller.py
test/core/test_utils.py

Arango controller (tested manually)
some utils for testing

Add some test rig stuff

---

.travis.yml
Dockerfile
Makefile
TODO.md
lib/SampleService/core/errors.py
lib/SampleService/core/sample.py
lib/SampleService/core/storage/arango_sample_storage.py
lib/SampleService/core/storage/errors.py
lib/SampleService/core/util.py
mypy.ini
test/core/arango_sample_storage_test.py
test/core/sample_test.py
test/test.cfg.example

Still needs more tests for current code, but getting this working was a
nightmare so committing

Get arango tests running

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Otherwise a bunch of other docs will be created and then have to be
cleaned up.

Check if the sample doc exists and bail on save

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Using a vertex collection where an edge collection is required causes silent
data modification

Add version edge collection & check col types

---

TODO.md
lib/SampleService/core/storage/arango_sample_storage.py

Also ensure that methods aren't returning cursors

Move arango cursor operations inside try/except

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Add index for node uuidvers

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

If the DB or server goes down after the version uuid is added to the sample doc
but before the integer versions are updated
on the version and node docs, on a get the service will update the integer
versions.

Correct partial updates on sample get

---

Pipfile
Pipfile.lock
lib/SampleService/core/storage/arango_sample_storage.py
mypy.ini
test/core/storage/arango_sample_storage_test.py

Add threaded db consistency checker

---

lib/SampleService/core/storage/arango_sample_storage.py

Document the philosophy behind the db schema

---

lib/SampleService/core/acls.py
lib/SampleService/core/arg_checkers.py
test/core/arg_checkers_test.py

Also accidentally added a chunk of acl code. Meh.

Add arg checker for iterables

---

lib/SampleService/SampleServiceImpl.py

Server is saying sample collection doesn't exist, which it does.

Debugging dynserver startup: print collections

---

lib/SampleService/SampleServiceImpl.py

Expose metadata in the API

---

lib/SampleService/SampleServiceImpl.py

Since the json module doesn't know how to handle it

Unfreeze node metadata

---

SampleService.spec
lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/api_arguments.py
lib/SampleService/core/core_types.py
lib/SampleService/core/sample.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/api_arguments_test.py

Easier to test
Also added a lot of error checking.

Move API -> core translation code into separate file

---

lib/SampleService/core/api_arguments.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/api_arguments_test.py

Can't index a list inside a list:
https://www.arangodb.com/docs/stable/indexing-index-basics.html#indexing-array-values

Flatten db metadata representation

---

lib/SampleService/core/api_arguments.py
test/core/api_arguments_test.py

Improve helper methods for getting sample addresses

---

lib/SampleService/core/acls.py
test/core/acls_test.py

For incoming ACL replacement, replacing owner is not allowed

Add an acl class that doesn't require an owner

---

Pipfile
Pipfile.lock
lib/SampleService/core/user_lookup.py
test/SampleService_test.py

Hits auth server to check usernames.
TODO:
1) cache (hence cacheout)
2) integrate into code

Add user lookup class

---

TODO.md
deploy.cfg
lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/errors.py
lib/SampleService/core/samples.py
lib/SampleService/core/user_lookup.py
test/SampleService_test.py
test/core/samples_test.py

Integrate user lookup / validation

---

lib/SampleService/core/sample.py
test/core/sample_test.py

key/value length, total size, control chars

Sanity checking on metadata

---

lib/SampleService/core/api_arguments.py
lib/SampleService/core/sample.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/sample_test.py
test/core/storage/arango_sample_storage_test.py

uncontrolled metadata -> user metadata

Align internal var names with external

---

Pipfile.lock
lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/api_arguments.py
lib/SampleService/core/errors.py
lib/SampleService/core/samples.py
test/core/samples_test.py

Still need to load configs from config file and pass in validator fns to
core code
Also add integration test for failing case

Add metadata validation to core code

---

deploy.cfg
lib/SampleService/core/config.py
test/core/config_test.py
test/core/config_test_vals.py

Loaded from config. Validators can be added without altering core code

Add metadata module validator loader function

---

Pipfile
Pipfile.lock
deploy.cfg
kbase.yml
lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/config.py
lib/SampleService/core/validators/builtin.py
mypy.ini
test/SampleService_test.py
test/core/config_test.py
test/core/validators/builtin_test.py

Load metadata validator config from a yaml file

---

lib/SampleService/core/config.py
test/SampleService_test.py
test/core/config_test.py

vs a single validator per metadata key

Make metadata validators a list in config

---

lib/SampleService/core/validators/builtin.py
test/SampleService_test.py
test/core/validators/builtin_test.py

checks type, maximum length, required keys. Can add features as necessary.

Make general string validator

---

README.md
lib/SampleService/core/validators/builtin.py
test/core/validators/builtin_test.py

Otherwise mispellings will be really annoying for users

Error on unknown validator config example

---

lib/SampleService/core/config.py
lib/SampleService/core/samples.py
lib/SampleService/core/validator/metadata_validator.py
test/SampleService_test.py
test/core/config_test.py
test/core/config_test_vals.py
test/core/samples_test.py
test/core/validators/metadata_validator_test.py

Makes changes easier, don't have to deal with the core code

refactor metadata validator into own class

---

Pipfile
Pipfile.lock
lib/SampleService/core/validator/metadata_validator.py
mypy.ini
test/core/validators/metadata_validator_test.py

Add prefix validators to metadata validator module

---

lib/SampleService/core/config.py
test/core/config_test.py

Ignore whitespace only entries in the comma separated list

Fix config bug

---

lib/SampleService/core/user_lookup.py
test/authjars

Can't update user_lookup.py to use new features until deployed, although
checked that they worked before commenting out

Test against latest version of auth server

---

lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/acls.py
lib/SampleService/core/api_arguments.py
lib/SampleService/core/api_translation.py
lib/SampleService/core/user_lookup.py
test/core/api_arguments_test.py

Also rename api_arguments to api_translation

Add admin checking helper function

---

test/core/api_translation_test.py

rename api_arguments_test to api_translation_test

---

lib/SampleService/core/config.py
lib/SampleService/core/samples.py
lib/SampleService/core/validator/metadata_validator.py
test/core/samples_test.py
test/core/validator/metadata_validator_test.py

Going to need to use MV for individual validators, getting too complicated
to not encapsulate them

Rename MetadataValidator to MetadataValidatorSet

---

lib/SampleService/core/validator/metadata_validator.py
test/core/validator/metadata_validator_test.py

Set class is getting too complicated with the advent of static metadata,
get ready to split it out

Add metadata validator class

---

lib/SampleService/core/workspace.py
lib/installed_clients/WorkspaceClient.py
lib/installed_clients/baseclient.py
mypy.ini
test/workspace_test.py

Add workspace permission checking method

---

lib/SampleService/core/workspace.py
test/SampleService_test.py
test/core/workspace_test.py
test/workspace_controller.py

includes workaround for workspace config reading bug, see
https://github.com/kbase/workspace_deluxe/issues/350

Add get_workspaces integration test

---

lib/SampleService/core/workspace.py
test/core/workspace_test.py

previously just checked ws perms
Still needs integration tests

Check if object exists when presented with upa

---

lib/SampleService/core/workspace.py
test/core/workspace_test.py

Easier to check once and pass around, and hope ppl aren't being jerks about
violating the constructor contract

Add UPA class

---

lib/SampleService/core/config.py
lib/SampleService/core/errors.py
lib/SampleService/core/storage/arango_sample_storage.py
test/SampleService_test.py
test/core/errors_test.py
test/core/storage/arango_sample_storage_test.py

Lots of TODOs just at this layer
After that, add all the non-db functionality from the design spec to the
business layer
Then expose in API

Save data links @ database layer

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

also match RE re created and expired
per @jayrbolton OOB review

make db fields more readable

---

lib/SampleService/core/data_link.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/data_link_test.py
test/core/storage/arango_sample_storage_test.py

previous idea of using DUID as ID doesn't work due to link expiration

Add link ID

---

test/core/storage/arango_sample_storage_test.py

reiterate save order for asserertions

Make link test easier to read

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

sample ver is a UUID controlled by the class, so is guaranteed to be a unique
ID for a ver

Reduce index size

---

lib/SampleService/core/storage/arango_sample_storage.py

Factor out transaction commit and abort methods

---

lib/SampleService/core/data_link.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/data_link_test.py
test/core/storage/arango_sample_storage_test.py

Otherwise expired links will prevent new links from being created
Also change expire/create -> expired/created in DataLink class, reads better

Give link different _key if expired

---

Makefile
lib/SampleService/core/storage/arango_sample_storage.py

Wipes out fixes to error handling

Don't compile server during build

---

lib/SampleService/core/data_link.py
test/core/data_link_test.py

Also check for impossible expire values

Add expire method to DataLInk

---

lib/SampleService/core/data_link.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

also make the _key use the create key vs expire key

Expire links

---

lib/SampleService/core/data_link.py
test/core/data_link_test.py

Just manipulate the dict version of the link directly now

Remove unused method

---

lib/SampleService/core/user.py
test/core/user_test.py

repeating myself too much at this point

Add a user class

---

Makefile
mypy.ini
test/arango_controller.py

turn on mypy for test files

---

lib/SampleService/core/validator/builtin.py
mypy.ini

Even with --namespace-packages won't recurse into directories without
`__init__.py`s.
Turns out there's a bunch of typing errors in `builtin.py `that weren't
detected.

turns out mypy is even jankier than I thought

---

lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/api_translation.py
lib/SampleService/core/sample.py
lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/api_translation_test.py
test/core/sample_test.py
test/core/samples_test.py
test/core/storage/arango_sample_storage_test.py

had  *lot* of knock on effects.

Use user ID class in Sample

---

lib/SampleService/SampleServiceImpl.py

when creating a sample.
Tested manually

Include impersonated user name in logs

---

lib/SampleService/core/data_link.py
test/core/data_link_test.py

equals checks too much for the use case I need

Add is_equivalent method to data link

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

That was a much bigger pain than expected...
Allows combination of expire and create methods when creating a link so
the user doesn't have to check for existence before creating a new link.

Update a link

---

lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

If you have access to an object, you have access to any linked samples per
the design doc.

Get links from ws object to samples

---

lib/SampleService/core/config.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/storage/arango_sample_storage_test.py

Will be needed for getting sample via a workspace object

Add has_data_link method to db layer

---

deploy.cfg
lib/SampleService/core/config.py
lib/SampleService/core/samples.py
lib/SampleService/core/storage/arango_sample_storage.py
lib/SampleService/core/workspace.py
test/SampleService_test.py
test/core/samples_test.py
test/core/workspace_test.py

* Integrates the workspace wrapper into the service. Not actually used yet,
but starts up.
* Uses the UserID class in the workspace client wrapper.

Use user class in workspace, integrate workspace

---

README.md
lib/SampleService/core/validator/builtin.py
test/core/validator/builtin_test.py

Does feck all but apparently helps easily confused people

Allow 'float' as a type for the number validator

---

lib/SampleService/core/api_translation.py
lib/SampleService/core/config.py
test/core/api_translation_test.py

Always required for getting link to avoid race conditions

Need required option for sample version

---

Dockerfile
Pipfile
Pipfile.lock

Tried lots of stuff, this combintation works. Using conda to upgrade
python completely screws up the python install.

Fix build; install py3.7 from source

---

lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/api_translation.py
lib/SampleService/core/user.py
test/SampleService_test.py
test/core/api_translation_test.py
test/core/user_test.py

Would allow creating a sample for a user that doesn't exist

Fix create sample admin bug

---

lib/SampleService/core/api_translation.py
lib/SampleService/core/samples.py
lib/SampleService/core/user_lookup.py
test/SampleService_test.py
test/core/api_translation_test.py
test/core/samples_test.py

makes more sense since it returns a list of invalid users

are_valid_users -> invalid_users

---

lib/SampleService/core/arg_checkers.py
lib/SampleService/core/storage/arango_sample_storage.py
test/core/arg_checkers_test.py
test/core/storage/arango_sample_storage_test.py

needed for admin mode for getting data links from  a sample

Allow not filtering on wsid in DB layer for get links

---

lgtm.yml

ID generated files causing alerts

Add lgtm.yml

---

TODO.md
lib/SampleService/core/storage/arango_sample_storage.py

* details on Kafka integration
* listing expired links
* search notes

Update TODO doc

---

Pipfile
Pipfile.lock
mypy.ini
test/kafka_controller.py

for testing.
Still needs a way to clear topics.
Next - make a kafka notifier class and test in the integration test class
against kafka.

Add Kafka controller

---

test/kafka_controller.py

Simpler constructor, and now have access to all bin files
Assumes the bin dir is unchanged and the other installs also have a bin dir
Also fix some unnecessary instance variables

supply kafka bin dir as arg vs exe files

---

test/kafka_controller.py

Intended to be run between tests

Method to clear a topic of all data

---

test/kafka_controller.py

Intended to be run between tests

Add method to clear data from all topics

---

.travis.yml
lib/SampleService/core/notification.py
test/SampleService_test.py
test/core/test_utils.py
test/kafka_controller.py
test/test.cfg.example

Only has 1 notification method for now, more coming.
Also need to integrate into service
Need to check topic for same characters.

Add Kafka notifier

---

lib/SampleService/core/notification.py
test/SampleService_test.py

Next integrate into core code, unit & integration tests

Add acl change to notification class

---

lib/SampleService/core/notification.py
lib/SampleService/core/samples.py
test/SampleService_test.py
test/core/samples_test.py

Also fix an (unlikely) race condition that could lead to expiring the
wrong link

Notify kafka when a link is expired

---

Makefile
lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/api_translation.py
test/SampleService_test.py
test/core/api_translation_test.py

Was hardcoded for sample IDs only

refactor id processing to support link ids

---

lib/SampleService/core/notification.py

Handle multiple Kafka bootstrap servers

---

deploy.cfg
kbase.yml
lib/SampleService/SampleServiceImpl.py
test/SampleService_test.py

also some whitespace fixes in deploy.cfg

bump version

---

lib/SampleService/core/workspace.py
test/core/workspace_test.py

Doesn't affect overall service behavior yet

Support anon users in ws wrapper 'get ws ids' method

---

test/SampleService_test.py

Tests that anon users can't see links to data in non-public read workspaces

Add anon user test for get links from sample

---

lib/SampleService/core/acls.py
test/core/acls_test.py

Value class that holds a set of deltas to be applied to
an ACL atomically

Add ACL delta class

---

lib/SampleService/core/acls.py
test/SampleService_test.py
test/core/acls_test.py
test/core/api_translation_test.py
test/core/samples_test.py

`__eq__` is incorrect otherwise

Sort acl lists in value class

---

lib/SampleService/core/acls.py

Will have a dependency on SACLDelta in the next PR

Move Sample ACL below SACLDelta

---

lib/SampleService/core/sample.py
test/core/api_translation_test.py
test/core/sample_test.py

...with source metadata.
Also try and make some of the error messages a little less confusing.

Refactor metadata basic checking code for reuse

---

lib/SampleService/core/api_translation.py
test/SampleService_test.py
test/core/api_translation_test.py

Also match up the source metadata value key name - svalue vs value
Next: update spec, add integration tests

Add source metadata to API translation layer in returned data

---

RELEASE_NOTES.md
deploy.cfg
deploy.cfg.tmpl
kbase.yml
lib/SampleService/SampleServiceImpl.py
lib/SampleService/core/api_translation.py
lib/SampleService/core/config.py
test/SampleService_test.py
test/core/api_translation_test.py

remove users associated with service tokens from the get_samples_acls method
https://kbase-jira.atlassian.net/browse/SCT-3079

remove service user from get acls

---

.github/workflows/build_prodrc_pr.yaml
.github/workflows/build_test_pr.yaml
.github/workflows/scripts/build_prodrc_pr.sh
.github/workflows/scripts/build_test_pr.sh
.github/workflows/scripts/deploy_tag.sh
.github/workflows/scripts/tag_environments.sh
.github/workflows/scripts/tag_prod_latest.sh
.github/workflows/scripts/tag_test_latest.sh
.github/workflows/tag_environments.yaml
.github/workflows/tag_prod_latest.yaml
.github/workflows/tag_test_latest.yaml

Adds .github workflows for:
- build/push image from any PR `#X` into `master` to `ghcr.io/kbase/sample_service:pr-X`
- build/push image from `master@HEAD` to `ghcr.io/kbase/sample_service:latest`
Also adds, but may not be needed:
- build/push image from any PR `#X` into `develop` to `ghcr.io/kbase/sample_service-develop:pr-X`
- build/push image from `develop@HEAD` to `ghcr.io/kbase/sample_service-develop:latest`

Add GHCR workflows

---

RELEASE_NOTES.md
kbase.yml
lib/SampleService/SampleServiceImpl.py
test/SampleService_test.py

Bumps verions from 0.1.1 to 0.2.1

Update version and release notes for get_data_links_from_sample_set

---

README.md

Add a few answers to questions that come up from time to time in this project.

Add contribution process guidelines.

---

RELEASE_NOTES.md
kbase.yml
lib/SampleService/SampleServiceImpl.py
test/SampleService_test.py

Update version and RELEASE_NOTES.md to version 0.2.5.

Release 0.2.5: SAM-119, SAM-209, SAM-236
